# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ml.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ml.proto',
  package='ml',
  syntax='proto3',
  serialized_pb=_b('\n\x08ml.proto\x12\x02ml\"(\n\x08\x41rtifact\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\"\x1e\n\x0f\x41rtifactRequest\x12\x0b\n\x03tar\x18\x01 \x01(\x0c\x32\x33\n\x05\x42oxer\x12*\n\x03Run\x12\x13.ml.ArtifactRequest\x1a\x0c.ml.Artifact\"\x00\x62\x06proto3')
)




_ARTIFACT = _descriptor.Descriptor(
  name='Artifact',
  full_name='ml.Artifact',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uuid', full_name='ml.Artifact.uuid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='ml.Artifact.status', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=56,
)


_ARTIFACTREQUEST = _descriptor.Descriptor(
  name='ArtifactRequest',
  full_name='ml.ArtifactRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tar', full_name='ml.ArtifactRequest.tar', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=88,
)

DESCRIPTOR.message_types_by_name['Artifact'] = _ARTIFACT
DESCRIPTOR.message_types_by_name['ArtifactRequest'] = _ARTIFACTREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Artifact = _reflection.GeneratedProtocolMessageType('Artifact', (_message.Message,), dict(
  DESCRIPTOR = _ARTIFACT,
  __module__ = 'ml_pb2'
  # @@protoc_insertion_point(class_scope:ml.Artifact)
  ))
_sym_db.RegisterMessage(Artifact)

ArtifactRequest = _reflection.GeneratedProtocolMessageType('ArtifactRequest', (_message.Message,), dict(
  DESCRIPTOR = _ARTIFACTREQUEST,
  __module__ = 'ml_pb2'
  # @@protoc_insertion_point(class_scope:ml.ArtifactRequest)
  ))
_sym_db.RegisterMessage(ArtifactRequest)



_BOXER = _descriptor.ServiceDescriptor(
  name='Boxer',
  full_name='ml.Boxer',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=90,
  serialized_end=141,
  methods=[
  _descriptor.MethodDescriptor(
    name='Run',
    full_name='ml.Boxer.Run',
    index=0,
    containing_service=None,
    input_type=_ARTIFACTREQUEST,
    output_type=_ARTIFACT,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_BOXER)

DESCRIPTOR.services_by_name['Boxer'] = _BOXER

# @@protoc_insertion_point(module_scope)
