# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import ml_pb2 as ml__pb2


class BoxerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Run = channel.unary_unary(
        '/ml.Boxer/Run',
        request_serializer=ml__pb2.ArtifactRequest.SerializeToString,
        response_deserializer=ml__pb2.Artifact.FromString,
        )


class BoxerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Run(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_BoxerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Run': grpc.unary_unary_rpc_method_handler(
          servicer.Run,
          request_deserializer=ml__pb2.ArtifactRequest.FromString,
          response_serializer=ml__pb2.Artifact.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'ml.Boxer', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
